### ISSUE TITLE
Question about i18n

### ISSUE THREAD

**Issue by PikachuEXE** [mezuka/enum#3]
In README there is:

``` yaml
en:
  enum:
    Side:
      left: 'Left'
      right: 'Right'
```

How does it handle namespaced classes?

Also in https://github.com/mezuka/enum/blob/master/lib/enum/base.rb#L67
I don't see any detection of `I18n` constant's presence

**Comment by ka8725** [comment]
H, @PikachuEXE , thanks for your questions!
1. About detection of `I18n` please read README - you will have understandable exception. 
2. It's possible to define any key in yaml:

``` yaml
en:
  enum:
    'Room::Side':
      left: 'Left'
      right: 'Right'
```

**Comment by sergeygaychuk** [comment]
I think we can add more appropriate translation:

``` yaml
en:
  enum:
    Room:
      Side: #Room::Side
        left: 'Left'
        right: 'Right'
```

What do you think @ka8725 ?
